# Generated by Django 5.2.9 on 2026-01-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('op', '운영자'), ('mg', '관리자'), ('tmp', '임시 사용자')], default='op', max_length=6),
        ),
    ]
