# Generated by Django 5.2.9 on 2026-01-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='made_by',
            field=models.CharField(db_index=True, default='Unknown', max_length=200),
        ),
    ]
