# Generated by Django 5.2.9 on 2026-01-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_product_made_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_display',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_order',
        ),
    ]
