# Generated by Django 5.2.9 on 2026-01-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/no-image.jpg', upload_to='products/%Y/%m/%d'),
        ),
    ]
