# Generated by Django 5.2.9 on 2026-01-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-category', 'name']},
        ),
    ]
