# Generated by Django 5.2.9 on 2026-01-10 02:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('script', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SysctlParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('office_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('compay_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSHInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=22)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.operator')),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('role_version', models.CharField(max_length=255)),
                ('ip_real', models.GenericIPAddressField()),
                ('os_version', models.CharField(max_length=100)),
                ('kernel_version', models.CharField(max_length=255)),
                ('cpu_cores', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_memory', models.PositiveSmallIntegerField()),
                ('total_disk', models.PositiveSmallIntegerField()),
                ('uptime', models.PositiveSmallIntegerField()),
                ('is_virtual', models.BooleanField(default=True)),
                ('is_master', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('server_roles', models.ManyToManyField(blank=True, to='asct.serverrole')),
                ('sshinfo', models.ManyToManyField(to='asct.sshinfo')),
            ],
            options={
                'ordering': ['hostname', '-created_at'],
                'unique_together': {('hostname', 'ip_real', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='NetworkUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_service', models.CharField(choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC')], default='1G', max_length=10)),
                ('network_service_inbound_bytes', models.DecimalField(decimal_places=2, max_digits=20)),
                ('network_service_outbound_bytes', models.DecimalField(decimal_places=2, max_digits=20)),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('serverinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['serverinfo__hostname', '-datetime'],
                'unique_together': {('serverinfo', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='MemoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('serverinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['serverinfo__hostname', '-datetime'],
                'unique_together': {('serverinfo', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_local_total', models.IntegerField()),
                ('storage_local_usage_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('serverinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['serverinfo__hostname', '-datetime'],
                'unique_together': {('serverinfo', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='CPUUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_percent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('serverinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['serverinfo__hostname', '-datetime'],
                'unique_together': {('serverinfo', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='SysctlSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.sysctlparameter')),
                ('serverinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['serverinfo', '-created_at'],
                'unique_together': {('serverinfo', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='ERROR', max_length=10)),
                ('log_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('serverinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asct.serverinfo')),
            ],
            options={
                'ordering': ['serverinfo', '-created_at'],
                'unique_together': {('serverinfo', 'created_at')},
            },
        ),
    ]
