# Generated by Django 5.2.9 on 2026-02-04 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('script', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('os', 'Operating System'), ('basic', 'Basic Shell'), ('app', 'Application'), ('traffic', 'Traffic'), ('sysctl', 'System ctl'), ('etc', '기타')], default='os', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SSHInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('login_id', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=22)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip1', models.GenericIPAddressField(blank=True, null=True)),
                ('ip2', models.GenericIPAddressField(blank=True, null=True)),
                ('os_version', models.CharField(max_length=100)),
                ('kernel_version', models.CharField(max_length=255)),
                ('cpu_cores', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('memory', models.PositiveSmallIntegerField()),
                ('total_disk', models.PositiveSmallIntegerField()),
                ('uptime', models.PositiveSmallIntegerField()),
                ('data_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('disk_usage', models.FloatField(blank=True, null=True)),
                ('is_virtual', models.BooleanField(default=True)),
                ('is_master', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('run_time', models.DateTimeField(auto_now_add=True)),
                ('roles', models.ManyToManyField(blank=True, to='asct.serverrole')),
                ('sshinfos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asct.sshinfo')),
            ],
            options={
                'ordering': ['hostname', '-data_time'],
            },
        ),
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asct.command')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ssh_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asct.sshinfo')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='CPUUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(default='127.0.0.0')),
                ('cpu_cores', models.PositiveSmallIntegerField(default=1)),
                ('usage_p', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('ssh_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asct.sshinfo')),
            ],
            options={
                'ordering': ['hostname', '-data_time'],
                'unique_together': {('hostname', 'ip', 'data_time')},
            },
        ),
    ]
