# Generated by Django 5.2.9 on 2026-02-07 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuusage',
            name='ssh_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asct.sshinfo'),
        ),
    ]
