# Generated by Django 5.2.9 on 2026-01-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='roles',
        ),
        migrations.AddField(
            model_name='operator',
            name='role',
            field=models.CharField(choices=[('op', '운영자'), ('mg', '관리자'), ('tmp', '임시 사용자')], default='op', max_length=10),
        ),
        migrations.DeleteModel(
            name='OperatorRole',
        ),
    ]
