# Generated by Django 5.2.9 on 2026-01-31 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0002_remove_operator_roles_operator_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
