# Generated by Django 5.2.9 on 2026-02-07 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0002_alter_cpuusage_ssh_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(default='127.0.0.0')),
                ('total_memory', models.PositiveIntegerField(default=0)),
                ('usage_p', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('ssh_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asct.sshinfo')),
            ],
            options={
                'ordering': ['hostname', '-data_time'],
                'unique_together': {('hostname', 'ip', 'data_time')},
            },
        ),
    ]
