# Generated by Django 5.2.9 on 2026-02-08 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0003_memoryusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(default='127.0.0.0')),
                ('if_name', models.CharField(default='eth0', max_length=20)),
                ('network_speed', models.CharField(choices=[('100M', '100M'), ('1G', '1G'), ('10G', '10G'), ('40G', '40G'), ('100G', '100G'), ('8G', '8G FC'), ('16G', '16G FC'), ('32G', '32G FC'), ('64G', '64G FC'), ('-', 'Not Available')], default='1G', max_length=6)),
                ('rxkB_s', models.DecimalField(decimal_places=2, max_digits=20)),
                ('txkB_s', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('ssh_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asct.sshinfo')),
            ],
            options={
                'ordering': ['hostname', '-data_time'],
                'unique_together': {('hostname', 'ip', 'data_time')},
            },
        ),
    ]
