# Generated by Django 5.2.9 on 2026-01-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asct', '0003_delete_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('script', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('os', 'Operatiion System Command'), ('basic', 'Basic Shell Command'), ('app', 'Application Command'), ('traffic', 'Traffic Command'), ('sysctl', 'System ctl Command'), ('etc', '기타')], default='os', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
