# Generated by Django 5.2.9 on 2026-02-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0004_networkusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkusage',
            name='network_speed',
            field=models.CharField(default='1G', max_length=10),
        ),
    ]
