# Generated by Django 5.2.9 on 2026-02-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0005_alter_networkusage_network_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkusage',
            old_name='network_speed',
            new_name='speed',
        ),
    ]
