# Generated by Django 5.2.9 on 2026-01-31 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0005_alter_command_category_sshinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshinfo',
            name='operator',
        ),
        migrations.AddField(
            model_name='sshinfo',
            name='operators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
