# Generated by Django 5.2.9 on 2026-01-31 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0006_remove_sshinfo_operator_sshinfo_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshinfo',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
