# Generated by Django 5.2.9 on 2026-02-09 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0006_rename_network_speed_networkusage_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(default='127.0.0.0')),
                ('storage_type', models.CharField(default='ssd', max_length=20)),
                ('local_total', models.IntegerField()),
                ('local_usage_p', models.DecimalField(decimal_places=2, max_digits=5)),
                ('checked_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('ssh_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asct.sshinfo')),
            ],
            options={
                'ordering': ['hostname', '-checked_at'],
                'unique_together': {('hostname', 'ip', 'checked_at')},
            },
        ),
    ]
