# Generated by Django 5.2.9 on 2026-02-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0007_diskusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskusage',
            name='storage_type',
        ),
        migrations.AddField(
            model_name='diskusage',
            name='mounted',
            field=models.CharField(default='ssd', max_length=20),
        ),
    ]
