# Generated by Django 5.2.9 on 2026-01-31 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0007_sshinfo_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asct.command')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ssh_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asct.sshinfo')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
