# Generated by Django 5.2.9 on 2026-02-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0008_remove_diskusage_storage_type_diskusage_mounted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskusage',
            name='mounted',
            field=models.CharField(default='ssd', max_length=255),
        ),
    ]
