# Generated by Django 5.2.9 on 2026-02-01 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0008_commandhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip1', models.GenericIPAddressField(blank=True, null=True)),
                ('ip2', models.GenericIPAddressField(blank=True, null=True)),
                ('os_version', models.CharField(max_length=100)),
                ('kernel_version', models.CharField(max_length=255)),
                ('cpu_cores', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('memory', models.PositiveSmallIntegerField()),
                ('total_disk', models.PositiveSmallIntegerField()),
                ('uptime', models.PositiveSmallIntegerField()),
                ('data_time', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_virtual', models.BooleanField(default=True)),
                ('is_master', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('sshinfos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asct.sshinfo')),
                ('roles', models.ManyToManyField(blank=True, to='asct.serverrole')),
            ],
            options={
                'ordering': ['hostname', '-data_time'],
            },
        ),
    ]
