# Generated by Django 5.2.9 on 2026-02-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0009_alter_diskusage_mounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskusage',
            name='local_total',
        ),
        migrations.AddField(
            model_name='diskusage',
            name='size',
            field=models.FloatField(default=0.0),
        ),
    ]
