# Generated by Django 5.2.9 on 2026-02-01 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0009_serverrole_serverinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='run_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='data_time',
            field=models.DateTimeField(),
        ),
    ]
