# Generated by Django 5.2.9 on 2026-02-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0010_serverinfo_run_time_alter_serverinfo_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='memory_usage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
