# Generated by Django 5.2.9 on 2026-02-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0010_remove_diskusage_local_total_diskusage_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskusage',
            name='local_usage_p',
        ),
        migrations.AddField(
            model_name='diskusage',
            name='use_p',
            field=models.IntegerField(default=0),
        ),
    ]
