# Generated by Django 5.2.9 on 2026-02-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0011_remove_diskusage_local_usage_p_diskusage_use_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskusage',
            name='devide',
            field=models.CharField(default='/dev', max_length=255),
        ),
        migrations.AlterField(
            model_name='diskusage',
            name='mounted',
            field=models.CharField(default='/', max_length=255),
        ),
    ]
