# Generated by Django 5.2.9 on 2026-02-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0012_diskusage_devide_alter_diskusage_mounted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diskusage',
            old_name='devide',
            new_name='device',
        ),
    ]
