# Generated by Django 5.2.9 on 2026-02-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asct', '0013_rename_devide_diskusage_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskusage',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
