--
-- PostgreSQL database dump
--

\restrict G0IXjZPhnCUv3iaTt1qqFEpHrQQJRoYpddlw6FjaHJ2R2OZF6ZS2wYJIH05Wahr

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asct_sshinfo_operators; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asct_sshinfo_operators (
    id bigint NOT NULL,
    sshinfo_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.asct_sshinfo_operators OWNER TO postgres;

--
-- Name: asct_sshinfo_operators_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asct_sshinfo_operators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asct_sshinfo_operators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: asct_sshinfo_operators; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asct_sshinfo_operators (id, sshinfo_id, user_id) FROM stdin;
5	4	3
6	4	84
7	5	3
8	5	84
9	6	3
10	6	84
14	4	4
15	5	4
16	6	4
18	8	4
19	8	84
20	9	84
21	9	4
22	9	5
23	8	5
\.


--
-- Name: asct_sshinfo_operators_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asct_sshinfo_operators_id_seq', 24, true);


--
-- Name: asct_sshinfo_operators asct_sshinfo_operators_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_sshinfo_operators
    ADD CONSTRAINT asct_sshinfo_operators_pkey PRIMARY KEY (id);


--
-- Name: asct_sshinfo_operators asct_sshinfo_operators_sshinfo_id_user_id_0aca4210_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_sshinfo_operators
    ADD CONSTRAINT asct_sshinfo_operators_sshinfo_id_user_id_0aca4210_uniq UNIQUE (sshinfo_id, user_id);


--
-- Name: asct_sshinfo_operators_sshinfo_id_2c46a406; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX asct_sshinfo_operators_sshinfo_id_2c46a406 ON public.asct_sshinfo_operators USING btree (sshinfo_id);


--
-- Name: asct_sshinfo_operators_user_id_3e749177; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX asct_sshinfo_operators_user_id_3e749177 ON public.asct_sshinfo_operators USING btree (user_id);


--
-- Name: asct_sshinfo_operators asct_sshinfo_operators_sshinfo_id_2c46a406_fk_asct_sshinfo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_sshinfo_operators
    ADD CONSTRAINT asct_sshinfo_operators_sshinfo_id_2c46a406_fk_asct_sshinfo_id FOREIGN KEY (sshinfo_id) REFERENCES public.asct_sshinfo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: asct_sshinfo_operators asct_sshinfo_operators_user_id_3e749177_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_sshinfo_operators
    ADD CONSTRAINT asct_sshinfo_operators_user_id_3e749177_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict G0IXjZPhnCUv3iaTt1qqFEpHrQQJRoYpddlw6FjaHJ2R2OZF6ZS2wYJIH05Wahr

