--
-- PostgreSQL database dump
--

\restrict AHNiJNHkUgGwUCfCzVBjaQ3wfCsUIV6v4d4eQ766BICRJHHr8X47QIvcJOJuzfn

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asct_commandhistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asct_commandhistory (
    id bigint NOT NULL,
    stdout text NOT NULL,
    stderr text NOT NULL,
    executed_at timestamp with time zone NOT NULL,
    command_id bigint,
    executed_by_id integer,
    ssh_info_id bigint NOT NULL
);


ALTER TABLE public.asct_commandhistory OWNER TO postgres;

--
-- Name: asct_commandhistory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asct_commandhistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asct_commandhistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: asct_commandhistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asct_commandhistory (id, stdout, stderr, executed_at, command_id, executed_by_id, ssh_info_id) FROM stdin;
3	2026-02-01 08:02\n		2026-02-01 08:02:46.21454+09	8	84	4
7	2026-02-01 08:06\n		2026-02-01 08:06:48.900578+09	8	84	4
8	Model name:          Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz\n		2026-02-01 08:10:54.799199+09	6	84	5
9	rhel9\n		2026-02-01 08:33:08.756512+09	1	84	6
10	 08:43:11 up 54 min,  0 users,  load average: 0.00, 0.00, 0.00\n		2026-02-01 08:43:11.357039+09	9	3	5
11	vm.overcommit_ratio = 50\n		2026-02-02 20:53:10.157169+09	14	84	5
12	Model name:                              Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz\n		2026-02-02 22:12:27.335348+09	6	84	6
\.


--
-- Name: asct_commandhistory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asct_commandhistory_id_seq', 12, true);


--
-- Name: asct_commandhistory asct_commandhistory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_commandhistory
    ADD CONSTRAINT asct_commandhistory_pkey PRIMARY KEY (id);


--
-- Name: asct_commandhistory_command_id_79fe6f5e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX asct_commandhistory_command_id_79fe6f5e ON public.asct_commandhistory USING btree (command_id);


--
-- Name: asct_commandhistory_executed_by_id_ab08c097; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX asct_commandhistory_executed_by_id_ab08c097 ON public.asct_commandhistory USING btree (executed_by_id);


--
-- Name: asct_commandhistory_ssh_info_id_e76eaabd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX asct_commandhistory_ssh_info_id_e76eaabd ON public.asct_commandhistory USING btree (ssh_info_id);


--
-- Name: asct_commandhistory asct_commandhistory_command_id_79fe6f5e_fk_asct_command_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_commandhistory
    ADD CONSTRAINT asct_commandhistory_command_id_79fe6f5e_fk_asct_command_id FOREIGN KEY (command_id) REFERENCES public.asct_command(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: asct_commandhistory asct_commandhistory_executed_by_id_ab08c097_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_commandhistory
    ADD CONSTRAINT asct_commandhistory_executed_by_id_ab08c097_fk_auth_user_id FOREIGN KEY (executed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: asct_commandhistory asct_commandhistory_ssh_info_id_e76eaabd_fk_asct_sshinfo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_commandhistory
    ADD CONSTRAINT asct_commandhistory_ssh_info_id_e76eaabd_fk_asct_sshinfo_id FOREIGN KEY (ssh_info_id) REFERENCES public.asct_sshinfo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict AHNiJNHkUgGwUCfCzVBjaQ3wfCsUIV6v4d4eQ766BICRJHHr8X47QIvcJOJuzfn

