--
-- PostgreSQL database dump
--

\restrict AlRCIczTXAjt3li40Eru3eJLPjKQACm4hnyDuxyOgvGsgvcFS1e7S4OkmExEDXS

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asct_serverrole; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asct_serverrole (
    id bigint NOT NULL,
    name character varying(20) NOT NULL,
    description character varying(100) NOT NULL
);


ALTER TABLE public.asct_serverrole OWNER TO postgres;

--
-- Name: asct_serverrole_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asct_serverrole ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asct_serverrole_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: asct_serverrole; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asct_serverrole (id, name, description) FROM stdin;
2	WAS	WAS Server
3	DB	DB Server
4	STORAGE	Storage Server
5	APP	Application Server
6	API	API Server
7	ETC	ETC Server
1	WEB	WEB Server
\.


--
-- Name: asct_serverrole_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asct_serverrole_id_seq', 7, true);


--
-- Name: asct_serverrole asct_serverrole_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_serverrole
    ADD CONSTRAINT asct_serverrole_name_key UNIQUE (name);


--
-- Name: asct_serverrole asct_serverrole_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_serverrole
    ADD CONSTRAINT asct_serverrole_pkey PRIMARY KEY (id);


--
-- Name: asct_serverrole_name_75963908_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX asct_serverrole_name_75963908_like ON public.asct_serverrole USING btree (name varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

\unrestrict AlRCIczTXAjt3li40Eru3eJLPjKQACm4hnyDuxyOgvGsgvcFS1e7S4OkmExEDXS

