--
-- PostgreSQL database dump
--

\restrict 7cUsE53UMf5xmP1PF2GQghUp8saht824EhGCwkMuXV8hHdUng8R3xhBAlqeDDcs

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asct_sshinfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asct_sshinfo (
    id bigint NOT NULL,
    login_id character varying(50) NOT NULL,
    ip inet NOT NULL,
    port integer NOT NULL,
    password character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.asct_sshinfo OWNER TO postgres;

--
-- Name: asct_sshinfo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asct_sshinfo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asct_sshinfo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: asct_sshinfo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asct_sshinfo (id, login_id, ip, port, password, created_at, updated_at, name) FROM stdin;
4	root	192.168.219.7	22	1	2026-01-31 22:26:37.203122+09	2026-01-31 22:29:52.473424+09	RHEL 7
5	root	192.168.219.111	22	1	2026-01-31 22:27:15.772474+09	2026-01-31 22:32:58.198183+09	RHEL 8
6	root	192.168.219.209	22	1	2026-01-31 22:27:55.403757+09	2026-01-31 22:33:12.999739+09	RHEL 9
8	root	192.168.219.206	22	1	2026-01-31 23:07:25.370862+09	2026-01-31 23:18:06.423645+09	RHEL 6
9	root	192.168.219.210	22	1	2026-01-31 23:14:08.069425+09	2026-02-01 08:39:04.996328+09	RHEL 10
\.


--
-- Name: asct_sshinfo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asct_sshinfo_id_seq', 9, true);


--
-- Name: asct_sshinfo asct_sshinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_sshinfo
    ADD CONSTRAINT asct_sshinfo_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict 7cUsE53UMf5xmP1PF2GQghUp8saht824EhGCwkMuXV8hHdUng8R3xhBAlqeDDcs

