--
-- PostgreSQL database dump
--

\restrict ntNp5FrHh27srRLkUOjlCbQcbJXePh8UYcn1cYYS2H0cdCG2C8cg7mVKLczydOW

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asct_command; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asct_command (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    script text NOT NULL,
    description text,
    category character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.asct_command OWNER TO postgres;

--
-- Name: asct_command_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asct_command ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asct_command_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: asct_command; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asct_command (id, name, script, description, category, created_at) FROM stdin;
1	hostname	hostname;		os	2026-01-31 12:12:15.754214+09
2	ip_address	hostname -I | awk '{print $1}';		os	2026-01-31 12:12:27.58397+09
4	kernel_version	uname -a | awk '{print $3}';		os	2026-01-31 12:12:51.997904+09
5	total_memory	free -m  | awk 'NR==2{print $2}';		os	2026-01-31 12:13:04.035091+09
9	uptime	uptime;		os	2026-01-31 12:13:46.350701+09
12	vm.dirty_background_ratio	sysctl vm.dirty_background_ratio;	sysctl vm.dirty_background_ratio;	sysctl	2026-01-31 12:14:34.993053+09
11	vm.dirty_ratio	sysctl vm.dirty_ratio;		sysctl	2026-01-31 12:14:06.287606+09
13	vm.overcommit_memory	sysctl vm.overcommit_memory;		sysctl	2026-01-31 12:14:45.715292+09
14	vm.overcommit_ratio	sysctl vm.overcommit_ratio;		sysctl	2026-01-31 12:14:55.910015+09
10	vm.swappiness	sysctl vm.swappiness;		sysctl	2026-01-31 12:13:56.05703+09
8	checked_date	date '+%Y-%m-%d %H:%M';	시스템에서 현재 시간을 추출	os	2026-01-31 12:13:37.310493+09
6	cpu_info	lscpu | grep "Model name:" | head -n 1;	cpu에 대한 모델 정보를 수집	os	2026-01-31 12:13:18.086027+09
\.


--
-- Name: asct_command_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asct_command_id_seq', 15, true);


--
-- Name: asct_command asct_command_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_command
    ADD CONSTRAINT asct_command_name_key UNIQUE (name);


--
-- Name: asct_command asct_command_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_command
    ADD CONSTRAINT asct_command_pkey PRIMARY KEY (id);


--
-- Name: asct_command_name_1ea6a6d7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX asct_command_name_1ea6a6d7_like ON public.asct_command USING btree (name varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

\unrestrict ntNp5FrHh27srRLkUOjlCbQcbJXePh8UYcn1cYYS2H0cdCG2C8cg7mVKLczydOW

