--
-- PostgreSQL database dump
--

\restrict pXczW4jfUkLqramT8ZVzTsIqGDMtJRggPpKpqIzQPKMeMOvWIiUDHS8nsmcGGTN

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asct_serverinfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asct_serverinfo (
    id bigint NOT NULL,
    hostname character varying(100) NOT NULL,
    ip1 inet,
    ip2 inet,
    os_version character varying(100) NOT NULL,
    kernel_version character varying(255) NOT NULL,
    cpu_cores smallint,
    memory smallint NOT NULL,
    total_disk smallint NOT NULL,
    uptime smallint NOT NULL,
    data_time timestamp with time zone NOT NULL,
    comment text,
    is_virtual boolean NOT NULL,
    is_master boolean NOT NULL,
    is_confirmed boolean NOT NULL,
    sshinfos_id bigint,
    run_time timestamp with time zone NOT NULL,
    cpu_usage double precision,
    disk_usage double precision,
    memory_usage double precision,
    CONSTRAINT asct_serverinfo_cpu_cores_check CHECK ((cpu_cores >= 0)),
    CONSTRAINT asct_serverinfo_memory_check CHECK ((memory >= 0)),
    CONSTRAINT asct_serverinfo_total_disk_check CHECK ((total_disk >= 0)),
    CONSTRAINT asct_serverinfo_uptime_check CHECK ((uptime >= 0))
);


ALTER TABLE public.asct_serverinfo OWNER TO postgres;

--
-- Name: asct_serverinfo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asct_serverinfo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asct_serverinfo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: asct_serverinfo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asct_serverinfo (id, hostname, ip1, ip2, os_version, kernel_version, cpu_cores, memory, total_disk, uptime, data_time, comment, is_virtual, is_master, is_confirmed, sshinfos_id, run_time, cpu_usage, disk_usage, memory_usage) FROM stdin;
2	r8	192.168.219.111	\N	Red Hat Enterprise Linux 8.10 (Ootpa)	4.18.0-553.78.1.el8_10.x86_64	4	3	44	0	2026-02-02 21:19:10+09		t	t	f	5	2026-02-01 13:52:30.318696+09	0	73	18.6
5	R10	192.168.219.210	\N	Red Hat Enterprise Linux 10.0 (Coughlan)	6.12.0-55.41.1.el10_0.x86_64	2	1	30	1	2026-02-02 21:24:56+09	\N	t	t	f	9	2026-02-01 13:53:34.721336+09	0	15	79.3
1	rhel7	192.168.219.7	\N	Red Hat Enterprise Linux Server 7.9 (Maipo)	3.10.0-1160.119.1.el7.x86_64	4	4	128	5	2026-02-02 21:48:03+09	\N	t	t	f	4	2026-02-01 13:51:37.809041+09	0.2	6	88.8
3	rhel9	192.168.219.209	\N	Red Hat Enterprise Linux 9.6 (Plow)	5.14.0-570.55.1.el9_6.x86_64	4	0	127	1	2026-02-02 21:56:05+09		t	t	t	6	2026-02-01 13:53:16.960262+09	0	6	77.6
4	rhel6	192.168.219.206	\N	Red Hat Enterprise Linux Server release 6.10 (Santiago)	2.6.32-754.35.1.el6.x86_64	2	4	20	1	2026-02-02 22:23:16+09	\N	f	t	f	8	2026-02-01 13:53:26.46818+09	0	19	85.1
\.


--
-- Name: asct_serverinfo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asct_serverinfo_id_seq', 5, true);


--
-- Name: asct_serverinfo asct_serverinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_serverinfo
    ADD CONSTRAINT asct_serverinfo_pkey PRIMARY KEY (id);


--
-- Name: asct_serverinfo_sshinfos_id_6eb8c916; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX asct_serverinfo_sshinfos_id_6eb8c916 ON public.asct_serverinfo USING btree (sshinfos_id);


--
-- Name: asct_serverinfo asct_serverinfo_sshinfos_id_6eb8c916_fk_asct_sshinfo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_serverinfo
    ADD CONSTRAINT asct_serverinfo_sshinfos_id_6eb8c916_fk_asct_sshinfo_id FOREIGN KEY (sshinfos_id) REFERENCES public.asct_sshinfo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict pXczW4jfUkLqramT8ZVzTsIqGDMtJRggPpKpqIzQPKMeMOvWIiUDHS8nsmcGGTN

