--
-- PostgreSQL database dump
--

\restrict hjPTgsfoRA5Y6mE1cUehOCbIgsXY303e02Y5QhnC5DMsn1aAYlp3IcSatPJlXLH

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asct_serverinfo_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asct_serverinfo_roles (
    id bigint NOT NULL,
    serverinfo_id bigint NOT NULL,
    serverrole_id bigint NOT NULL
);


ALTER TABLE public.asct_serverinfo_roles OWNER TO postgres;

--
-- Name: asct_serverinfo_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asct_serverinfo_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asct_serverinfo_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: asct_serverinfo_roles asct_serverinfo_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_serverinfo_roles
    ADD CONSTRAINT asct_serverinfo_roles_pkey PRIMARY KEY (id);


--
-- Name: asct_serverinfo_roles asct_serverinfo_roles_serverinfo_id_serverrole_id_c48dc92d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_serverinfo_roles
    ADD CONSTRAINT asct_serverinfo_roles_serverinfo_id_serverrole_id_c48dc92d_uniq UNIQUE (serverinfo_id, serverrole_id);


--
-- Name: asct_serverinfo_roles_serverinfo_id_5cb542c4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX asct_serverinfo_roles_serverinfo_id_5cb542c4 ON public.asct_serverinfo_roles USING btree (serverinfo_id);


--
-- Name: asct_serverinfo_roles_serverrole_id_d97e9125; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX asct_serverinfo_roles_serverrole_id_d97e9125 ON public.asct_serverinfo_roles USING btree (serverrole_id);


--
-- Name: asct_serverinfo_roles asct_serverinfo_role_serverinfo_id_5cb542c4_fk_asct_serv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_serverinfo_roles
    ADD CONSTRAINT asct_serverinfo_role_serverinfo_id_5cb542c4_fk_asct_serv FOREIGN KEY (serverinfo_id) REFERENCES public.asct_serverinfo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: asct_serverinfo_roles asct_serverinfo_role_serverrole_id_d97e9125_fk_asct_serv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asct_serverinfo_roles
    ADD CONSTRAINT asct_serverinfo_role_serverrole_id_d97e9125_fk_asct_serv FOREIGN KEY (serverrole_id) REFERENCES public.asct_serverrole(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict hjPTgsfoRA5Y6mE1cUehOCbIgsXY303e02Y5QhnC5DMsn1aAYlp3IcSatPJlXLH

